Fix #130 #131: Remove interfaces & getters
yiisoft/router pull request #138
Opened 2021-12-22 16:30 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️
| Fixed issues  | #130 #131

2021-12-22 19:28 UTC, samdark commented on src/Group.php
> +    public const PREFIX = 'prefix';
Not sure these constants are needed because they are in the middle of autocomplete list when defining routes.

2021-12-22 19:28 UTC, samdark commented on src/Group.php
> +        $dataMap = $this->getDataMap();
Good old `switch` would be more suitable here.

2021-12-22 19:28 UTC, samdark commented on src/Route.php
> +    public const NAME = 'name';
Not sure these are needed. We don't want people to use these.

2021-12-22 19:28 UTC, samdark commented on src/Route.php
> +        $dataMap = $this->getDataMap();
`switch` would be more suitable.

2021-12-22 19:34 UTC, samdark commented on src/Route.php
> +        return $dataMap[$key] ?? null;
It is better to throw an exception instead of returning null in this case.

2021-12-23 07:38 UTC, yiiliveext commented on src/RouteCollection.php
> +        $routeName = $route->getData('name');
```suggestion
        $routeName = $route->getData('name'); 
        $this->items[] = $routeName;        
```

2021-12-23 13:00 UTC, vjik requested changes

2021-12-23 13:00 UTC, vjik commented on src/CurrentRoute.php
> +    public function setRoute(Route $route): void
Suggestion: merge methods `setRoute()` and `setArguments` to one method, because in router they used in one place one after the other.

2021-12-23 13:00 UTC, vjik commented on src/Group.php
> +     * @return array
Suggestion: get middleware definitions also via `getData()`

2021-12-23 13:00 UTC, vjik commented on src/Route.php
> +    public function getData(string $key)
Suggestion: check has middlewares also via `getData()`

2021-12-23 13:00 UTC, vjik commented on .phpstorm.meta.php/Group.php
> +    use Yiisoft\Router\Group;
PhpStorm don't support section `use`.

2021-12-23 13:00 UTC, vjik commented on .phpstorm.meta.php/Route.php
> +    use Yiisoft\Router\Route;
PhpStorm don't support section `use`.

2021-12-24 07:17 UTC, samdark approved these changes

2021-12-24 11:43 UTC, merged