Added `Route` attribute for Yii Hydrator
yiisoft/router pull request #203
Opened 2023-05-15 12:24 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | -

2023-05-16 08:47 UTC, samdark approved these changes

2023-05-16 13:22 UTC, xepozz requested changes
`Route` is a wrong name for this kind of attribute.

`Route` is already reserved for routing: the class and coming attribute as well. 
I suggest you think about `RouteAttribute` or something similar. Do not confuse developers with one more `Route` entity.

2023-10-14 17:49 UTC, xepozz commented
Why is it `argument`, isn't `parameter` better?

2023-11-10 13:47 UTC, vjik commented
> Why is it `argument`, isn't `parameter` better?

In router, this is called "arguments": https://github.com/yiisoft/router/blob/0892cbebfdfbe73ae9d2a64a133c96daf1552c7a/src/CurrentRoute.php#L112

2024-01-29 06:19 UTC, samdark approved these changes

2024-01-29 06:19 UTC, samdark commented on composer.json
> +        "yiisoft/hydrator": "dev-master",
```suggestion
        "yiisoft/hydrator": "^1.0",
```

2024-01-29 17:10 UTC, merged