New syntax
yiisoft/router pull request #225
Opened 2023-11-09 07:22 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | #193, #171

2023-11-12 08:46 UTC, vjik requested changes
1) #191 suggest use named arguments, and this must improve performance. In this PR keep routes/groups object and additional add new routes/groups objects with named arguments. Seems, this decrease performance...

2) This not fix #171.

2023-11-12 18:07 UTC, rustamwin commented
> In this PR keep routes/groups object and additional add new routes/groups objects with named arguments. Seems, this decrease performance...

We can mention it in docs or drop the current syntax.

> This not fix https://github.com/yiisoft/router/issues/171.

Yes, doesn't fix directly. Since there is no exception, there is no need for it.

2023-11-22 17:23 UTC, vjik commented
> We can mention it in docs or drop the current syntax.

But what goal of syntax change?

2025-11-02 16:24 UTC, vjik requested changes
Can we make `Route` and `Group` constructors public and keep BC? 

I think, `GroupBuilder` and `RouteBuilder` are not needed.

2025-11-07 06:59 UTC, rustamwin commented
> Can we make Route and Group constructors public

Did you mean builders? Route and Group constructors are public in this PR.

> I think, GroupBuilder and RouteBuilder are not needed.

Will we abandon the current syntax?

2025-11-07 08:14 UTC, vjik commented
> > Can we make Route and Group constructors public
> 
> Did you mean builders? Route and Group constructors are public in this PR.

No, I mean `Yiisoft\Router\Router` and `Yiisoft\Router\Group`

> > I think, GroupBuilder and RouteBuilder are not needed.
> 
> Will we abandon the current syntax?

Mark as deprecated, then remove in major version.

2025-11-13 06:02 UTC, rustamwin commented
> Mark as deprecated, then remove in major version.

Let's abandon right away since the PR has major changes.

2025-11-13 07:59 UTC, vjik commented
> Let's abandon right away since the PR has major changes.

What major changes are needed?

2026-07-24 12:41 UTC, samdark commented
@rustamwin resolving of conflicts is needed.

2026-07-29 22:11 UTC, samdark commented on README.md
> +use Yiisoft\Router\Builder\RouteBuilder as Route;
We can avoid changing syntax by introducing static facades into old classes.

`Route::get()`, `post()`, `methods()`, etc. would return `RouteBuilder`, while `Group::create()` would return `GroupBuilder`. The public constructors would still create mutable data objects:

```php
$route = new Route([Method::GET], '/users');
```

2026-07-29 22:35 UTC, samdark commented
I also think we can keep backwards compatibility and mark some methods as deprecated but not sure it's needed.

2026-09-08 16:07 UTC, closed without merging